name: Deploy DAG with SSH

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on:
      - self-hosted
      - Linux
      - X64
      - org-level


    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy DAGs via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_NFS_HOST }}
          username: ${{ secrets.SSH_NFS_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            # Copy DAGs to Airflow's DAG directory
            cp dags/* /mnt/airflow/dags/
